defaults:
  - actor_critic.yaml
  - _self_

name: "DDPG"
horizon_len: 1
memory_size: 5e6
batch_size: 8192
nstep: 3
tau: 0.05
gamma: 0.99
warm_up: 32
act_class: TanhMLPPolicy
cri_class: DoubleQ
eval_freq: 100

update_times: 8
no_tgt_actor: True

noise:
  type: 'mixed' # ['fixed', 'mixed']
  decay: null  #  "exp" and "linear"
  exp_decay_rate: 0.99
  lin_decay_iters: 10000
  std_max: 0.8
  std_min: 0.05
  tgt_pol_std: 0.8
  tgt_pol_noise_bound: 0.2

